-- MySQL Script generated by MySQL Workbench
-- Wed Oct  5 22:15:59 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema worm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema worm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `worm` DEFAULT CHARACTER SET utf8mb4 ;
USE `worm` ;

-- -----------------------------------------------------
-- Table `worm`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worm`.`locations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worm`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worm`.`rooms` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `location_id` INT UNSIGNED NOT NULL,
  `floor` TINYINT(3) UNSIGNED NOT NULL,
  `number` TINYINT(3) UNSIGNED NOT NULL,
  `capacity` TINYINT(4) UNSIGNED NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rooms_location_id_idx` (`location_id` ASC),
  CONSTRAINT `fk_rooms_location_id`
    FOREIGN KEY (`location_id`)
    REFERENCES `worm`.`locations` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worm`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worm`.`courses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `description` TEXT NOT NULL,
  `credit` SMALLINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worm`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worm`.`teachers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(16) NOT NULL,
  `first_name` VARCHAR(64) NOT NULL,
  `last_name` VARCHAR(64) NOT NULL,
  `gender` VARCHAR(32) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worm`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worm`.`classes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `course_id` INT UNSIGNED NOT NULL,
  `room_id` INT UNSIGNED NOT NULL,
  `teacher_id` INT UNSIGNED NOT NULL,
  `datetime` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_classes_course_id_idx` (`course_id` ASC),
  INDEX `fk_classes_room_id_idx` (`room_id` ASC),
  INDEX `fk_classes_teacher_id_idx` (`teacher_id` ASC),
  CONSTRAINT `fk_classes_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `worm`.`courses` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_classes_room_id`
    FOREIGN KEY (`room_id`)
    REFERENCES `worm`.`rooms` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_classes_teacher_id`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `worm`.`teachers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worm`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worm`.`students` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(64) NOT NULL,
  `last_name` VARCHAR(64) NOT NULL,
  `birthday` DATETIME NULL,
  `gender` VARCHAR(32) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worm`.`classes_students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worm`.`classes_students` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `class_id` INT UNSIGNED NOT NULL,
  `student_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_classes_students_class_id_idx` (`class_id` ASC),
  INDEX `fk_classes_students_student_id_idx` (`student_id` ASC),
  CONSTRAINT `fk_classes_students_class_id`
    FOREIGN KEY (`class_id`)
    REFERENCES `worm`.`classes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_classes_students_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `worm`.`students` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `worm`.`locations`
-- -----------------------------------------------------
START TRANSACTION;
USE `worm`;
INSERT INTO `worm`.`locations` (`id`, `name`, `address`) VALUES (1, 'Campus 1', '1234 Budapest, Campus u. 123');
INSERT INTO `worm`.`locations` (`id`, `name`, `address`) VALUES (2, 'Campus 2', '1234 Berlin, Campus strasse 456');
INSERT INTO `worm`.`locations` (`id`, `name`, `address`) VALUES (3, 'Campus 3', '1234 Paris, rue de Campus 789');

COMMIT;


-- -----------------------------------------------------
-- Data for table `worm`.`rooms`
-- -----------------------------------------------------
START TRANSACTION;
USE `worm`;
INSERT INTO `worm`.`rooms` (`id`, `name`, `location_id`, `floor`, `number`, `capacity`, `description`) VALUES (1, 'Lab 1', 1, 1, 111, 25, 'Lab for 25 people');
INSERT INTO `worm`.`rooms` (`id`, `name`, `location_id`, `floor`, `number`, `capacity`, `description`) VALUES (2, 'Lab 2', 1, 2, 121, 50, 'Lab for 50 people');
INSERT INTO `worm`.`rooms` (`id`, `name`, `location_id`, `floor`, `number`, `capacity`, `description`) VALUES (3, 'Room 1', 2, 1, 211, 100, 'Room for lectures');
INSERT INTO `worm`.`rooms` (`id`, `name`, `location_id`, `floor`, `number`, `capacity`, `description`) VALUES (4, 'Room 2', 2, 1, 212, 250, 'Room for lectures');
INSERT INTO `worm`.`rooms` (`id`, `name`, `location_id`, `floor`, `number`, `capacity`, `description`) VALUES (5, 'Room 3', 2, 2, 221, 10, 'Lab for 10 people');
INSERT INTO `worm`.`rooms` (`id`, `name`, `location_id`, `floor`, `number`, `capacity`, `description`) VALUES (6, 'Auditorium Maximum', 2, 3, 231, 500, 'Auditorium Maximum');
INSERT INTO `worm`.`rooms` (`id`, `name`, `location_id`, `floor`, `number`, `capacity`, `description`) VALUES (7, 'Lab 1', 3, 1, 311, 25, 'Lab for 25 people');
INSERT INTO `worm`.`rooms` (`id`, `name`, `location_id`, `floor`, `number`, `capacity`, `description`) VALUES (8, 'Room 1', 3, 1, 312, 100, 'Room for 100 people');

COMMIT;


-- -----------------------------------------------------
-- Data for table `worm`.`teachers`
-- -----------------------------------------------------
START TRANSACTION;
USE `worm`;
INSERT INTO `worm`.`teachers` (`id`, `title`, `first_name`, `last_name`, `gender`) VALUES (1, 'prof', 'István', 'Kiss', 'male');
INSERT INTO `worm`.`teachers` (`id`, `title`, `first_name`, `last_name`, `gender`) VALUES (2, 'dr', 'János', 'Nagy', 'male');
INSERT INTO `worm`.`teachers` (`id`, `title`, `first_name`, `last_name`, `gender`) VALUES (3, 'dr', 'Ágnes', 'Kovács', 'female');
INSERT INTO `worm`.`teachers` (`id`, `title`, `first_name`, `last_name`, `gender`) VALUES (4, 'habil', 'Franz', 'Ferdinand', 'male');
INSERT INTO `worm`.`teachers` (`id`, `title`, `first_name`, `last_name`, `gender`) VALUES (5, ' ', 'Albert', 'Einstandt', 'male');
INSERT INTO `worm`.`teachers` (`id`, `title`, `first_name`, `last_name`, `gender`) VALUES (6, 'prof', 'Edith', 'Dubois', 'female');
INSERT INTO `worm`.`teachers` (`id`, `title`, `first_name`, `last_name`, `gender`) VALUES (7, 'phd', 'Luc', 'Henry', 'male');

COMMIT;

